apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: anp2
spec:
  priority: 2
  subject:
    namespaces: {}
  ingress:
  - name: "development-ns"
    action: "Pass"
    from:
    - namespaces:
        namespaceSelector:
          matchLabels:
            development: "true"
