apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  labels:
    pod: b
  name: b
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --tcp
    - --http=false
    - --port
    - "80"
    image: registry.k8s.io/e2e-test-images/agnhost:2.43
    imagePullPolicy: IfNotPresent
    name: cont-80-tcp
    ports:
    - containerPort: 80
      name: serve-80-tcp
      protocol: TCP
  - command:
    - /agnhost
    - serve-hostname
    - --tcp
    - --http=false
    - --port
    - "81"
    image: registry.k8s.io/e2e-test-images/agnhost:2.43
    imagePullPolicy: IfNotPresent
    name: cont-81-tcp
    ports:
    - containerPort: 81
      name: serve-81-tcp
      protocol: TCP
