project_name: policy-assistant
release:
  github:
    owner: huntergregory
    name: pola
builds:
  - id: pola
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/pola/main.go
    ldflags: -s -w
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.version={{.Version}}
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.gitSHA={{.Commit}}
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: "pola"
    hooks: {}
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    ids:
      - pola
    image_templates:
      - "docker.io/pola:latest" # FIXME use a real image repository
      - "docker.io/pola:{{ .Tag }}" # FIXME use a real image repository
    skip_push: false
    dockerfile: cmd/pola/Dockerfile
#    build_flag_templates:
#      - "--label=org.opencontainers.image.created={{.Date}}"
#      - "--label=org.opencontainers.image.title={{.ProjectName}}"
#      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#      - "--label=org.opencontainers.image.version={{.Version}}"
#      - "--pull"
#      - "--platform=linux/arm64"
archives:
  - id: pola
    builds:
      - pola
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENCE*
      - README*
      - CHANGELOG*
checksum:
  name_template: "pola_{{ .RawVersion }}_checksums.txt"
  algorithm: sha256
