project_name: policy-assistant
release:
  github:
    owner: kubernetes-sigs
    name: network-policy-api
builds:
  - id: policy-assistant
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/policy-assistant/main.go
    ldflags: -s -w
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.version={{.Version}}
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.gitSHA={{.Commit}}
      -X sigs.k8s.io/network-policy-api/policy-assistant/pkg/cli.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: "policy-assistant"
    hooks: {}
# commenting out since we don't have GHCR Images yet (see #263)
# dockers:
#   -
#     goos: linux
#     goarch: amd64
#     goarm: ''
#     ids:
#       - policy-assistant
#     image_templates:
#       - "docker.io/policy-assistant:latest" # FIXME use a real image repository
#       - "docker.io/policy-assistant:{{ .Tag }}" # FIXME use a real image repository
#     skip_push: false
#     dockerfile: cmd/policy-assistant/Dockerfile
# #    build_flag_templates:
# #      - "--label=org.opencontainers.image.created={{.Date}}"
# #      - "--label=org.opencontainers.image.title={{.ProjectName}}"
# #      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
# #      - "--label=org.opencontainers.image.version={{.Version}}"
# #      - "--pull"
# #      - "--platform=linux/arm64"
archives:
  - id: policy-assistant
    builds:
      - policy-assistant
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
checksum:
  name_template: "policy-assistant_v{{ .Version }}_checksums.txt"
  algorithm: sha256
