apiVersion: batch/v1
kind: Job
metadata:
  name: policy-assistant
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - command:
            - ./policy-assistant
            - generate
            - --ignore-loopback=true
            - --exclude=named-port,multi-peer,upstream-e2e,example
            - --job-timeout-seconds=2
          name: policy-assistant
          imagePullPolicy: IfNotPresent
          image: docker.io/policy-assistant:latest # FIXME use a real image repository
      serviceAccount: policy-assistant
