name: Kind CNI From Job
on:
  workflow_dispatch:
    inputs:
      cni:
        description: "name of CNI to use"
        required: true

jobs:
  test-kind-calico:
    name: Run pola on KinD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run pola
        working-directory: hack/kind
        run: CNI=${{ github.event.inputs.cni }} RUN_FROM_SOURCE=false ./run-pola.sh
