name: Kind Cilium policy-assistant
on:
  workflow_dispatch:
    inputs:
      pola_args:
        description: "args to pass on to policy-assistant"
        required: false
        default: "generate --include conflict --job-timeout-seconds 2 --server-protocol=tcp,udp --ignore-loopback=true"
#  schedule:
    # At 03:00 on Sunday.
#    - cron: '0 3 * * 0'

jobs:
  test-kind-cilium:
    name: Run policy-assistant on KinD/Cilium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run policy-assistant
        working-directory: hack/kind
        run: CNI=cilium RUN_FROM_SOURCE=true FROM_SOURCE_ARGS="${{ github.event.inputs.pola_args }}" ./run-policy-assistant.sh
